package room.dt.light;

import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;

/**
 * Light sensor Digital Twin Java API for the Application Layer
 *
 */
public interface LightDTAPI {
	
	
	/**
	 * 
	 * Get the current state of the light
	 * 
	 */
	Future<JsonObject> getState();

	/**
	 * 
	 * Get the event history
	 * 
	 */
	Future<JsonArray> getHistory();
	

	/**
	 * Subscribe to events generated by the light digital twin
	 * 
	 * @param handler
	 * @return
	 */
	Future<Void> subscribe(Handler<JsonObject> handler);
}
