package room.pa.detector;

import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;

/**
 * Toy Detector Thing API 
 *
 */
public interface DetectorThingAPI {
	
	/**
	 * Get the TD
	 */
	Future<JsonObject> getTD();
	
	/* properties */

	Future<Boolean> isDetected();
	
	/**
	 * Subscribe to events generated by the detector device
	 * 
	 * @param handler
	 * @return
	 */
	Future<Void> subscribe(Handler<JsonObject> handler);
}
